# Generated by Django 4.1.2 on 2022-10-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caballista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_caballista', models.CharField(max_length=20)),
                ('punto1', models.IntegerField(default=0)),
                ('punto2', models.IntegerField(default=0)),
            ],
        ),
    ]
